version: '3.1'
services:

  php-cli:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app

  composer:
    container_name: composer
    image: composer:latest
    profiles: [ "composer" ]
    command: /bin/bash -c composer
    volumes:
      - ./:/app

  phpunit:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: vendor/bin/phpunit